# Generated by Django 5.1.4 on 2025-01-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_orderitem_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
